### PR TITLE
In cubejs-schema-compiler joi@10.6.0 upgrade to joi@14.3.1

### LINKED ISSUE #47: Fix dependency warning in schema compiler (joi)
I get the following warning for `@cubejs-backend/server-core`: `@cubejs-backend/schema-compiler` > `joi@10.6.0`: This version is no longer maintained. Please upgrade to the latest version.

### PR DESCRIPTION
**Pull request by manojown**
resolve #47

Fix dependency warning in schema compiler .

Current ```joi@10.6``` version is deprecated so upgrade to latest ```joi@14.3.1``` .

### CODE REVIEW

**Comment by paveltiunov** [comment]
@manojown That was fast! 👍 Could you please confirm that `$ npm test` in schema compiler runs successfully?

**Comment by manojown** [comment]
hey @paveltiunov its failing by  Error: connect ECONNREFUSED 127.0.0.1:5432 .
what other services need to start for cubejs-schema-compiler .

**Comment by manojown** [comment]
@paveltiunov  run ```npm test``` command and schema compiler runs successfully . 
Screen Shot 2019-03-29 at 5 23 14 PM

**Comment by paveltiunov** [comment]
@manojown Good to hear that you figured it out! Thanks for contributing this!

**Pull request merged**
