### PR TITLE
force escape cubeAlias to work with restricted column names

### PR DESCRIPTION
**Pull request by dgkmurthy**
> force escape cubeAlias to work with restricted column names such as "case" in the column name

### CODE REVIEW

**Comment by paveltiunov** [comment]
@dgkmurthy Hey Keshava! Thanks for contributing this one! Just checked: it fails tests. Could you please fix it?

**Comment by dgkmurthy** [comment]
> @dgkmurthy Hey Keshava! Thanks for contributing this one! Just checked: it fails tests. Could you please fix it?

@paveltiunov, I will double check. Any particular test scenarios you are referring to?

**Comment by paveltiunov** [comment]
@dgkmurthy It's filter join not multiplied and MongoDB tests.

**Comment by dgkmurthy** [comment]
> @dgkmurthy It's filter join not multiplied and MongoDB tests.

@paveltiunov As of now I can only test again Postgres.  I have reverted changes and applied to only Postgres Query part.  Can you please check?

**Comment by paveltiunov** [comment]
@dgkmurthy Hey Keshava! Actually your first change was correct. You just need to fix this line: https://github.com/statsbotco/cube.js/blob/d22a809059340e2b7caab7dc8cb122c14e581edd/packages/cubejs-schema-compiler/adapter/BaseQuery.js#L589 . There's double escaping.

**Comment by dgkmurthy** [comment]
> @dgkmurthy Hey Keshava! Actually your first change was correct. You just need to fix this line:
> 
> https://github.com/statsbotco/cube.js/blob/d22a809059340e2b7caab7dc8cb122c14e581edd/packages/cubejs-schema-compiler/adapter/BaseQuery.js#L589
> 
> There's double escaping.

Ok great, can you please check the update now?

**Comment by paveltiunov** [comment]
@dgkmurthy Looks good! Thanks!

**Pull request merged**
