### PR TITLE
API documentation for CubejsServerCore.create(options)

### PR DESCRIPTION
**Pull request by dtslvr**
How to embed Cubejs in an Express application.

### CODE REVIEW

**Comment by keydunov** [comment]
@dtslvr Thanks! 

Do you mind to create a sub-sections inside an API?  One for frontend and one for the backend. All docs we have now under API section are for Frontend, and your additions are for Backend. It would be great to have them separated by sections. I'd expect more docs for both sections soon and it would be great to have the structure in place.

**Comment by dtslvr** [comment]
Good idea, keydunov. I have reorganized it in frontend and backend now.

**Comment by keydunov** [comment]
@dtslvr Great 👍

**Comment by dtslvr** [comment]
> @dtslvr Great 👍

You're welcome, @keydunov

**Pull request merged**
