### PR TITLE
Fix to discard the FR Columns from inclusion in the measures

### PR DESCRIPTION
**Pull request by dgkmurthy**
Fix to discard the Foreign Reference Columns from inclusion in the measures while generating the schema

### CODE REVIEW

**Comment by paveltiunov** [comment]
@dgkmurthy Hey Keshava! Thanks for posting this! Could you please provide some example use case which is fixed by this change? Preferably in the form of unit test.

**Comment by dgkmurthy** [comment]
> @dgkmurthy Hey Keshava! Thanks for posting this! Could you please provide some example use case which is fixed by this change? Preferably in the form of unit test.

Updated the existing unit tests to cover this change

**Comment by dgkmurthy** [comment]
The last change will ensure that the columns having 'id' suffix not included in the measures, and also, the measure fields to match dictionary for suffix only not between.

**Comment by paveltiunov** [comment]
Looks good! Thanks!

**Pull request merged**
